config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  patch 'users/confirmation_email', to: 'users#confirmation_email', as: 'user_confirmation_email'

  concern :votable do
    resources :votes, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  resource :search, only: [:show]

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/shared/_navbar.html.erb
<nav class="nav has-shadow">
  <div class="container">
    <div class="nav-left">
      <a class="nav-item">
        QandA
      </a>
      <%= link_to 'Questions', questions_path, class: 'nav-item is-tab is-hidden-mobile is-active' %>
    </div>
    <div class="nav-right nav-menu">
      <%= render 'shared/search_form' %>
      <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-item is-tab") %>
      <% else %>
          <%= link_to('Login', new_user_session_path, class: "nav-item is-tab")  %>
          <%= link_to('Sign up', new_user_registration_path, class: "nav-item is-tab")  %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_search_form.html.slim
.nav-item
  = form_tag search_path, method: :get
    .field
      = text_field_tag :q, params[:q], class: 'input', placeholder: "Find a ..."
      = submit_tag 'Search', class: 'button is-info is-outlined'