config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  patch 'users/confirmation_email', to: 'users#confirmation_email', as: 'user_confirmation_email'

  concern :votable do
    resources :votes, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  resource :search, only: [:show]

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include HasUser
  include Attachable
  include Votable
  include Commentable
  belongs_to :question

  validates :body, presence: true, length: { minimum: 10 }

  scope :first_best, -> { order('best DESC') }

  after_create :notify

  def mark_best
    ActiveRecord::Base.transaction do
      question.answers.where(best: true).find_each { |answer| answer.update!(best: false) }
      update!(best: true)
    end
  end

  private

  def notify
    SubscriptionQuestionJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :mark_best, :destroy]
  before_action :set_answer, only: [:update, :mark_best, :destroy]
  before_action :set_question, only: [:create]

  after_action :publish_answer, only: [:create]

  authorize_resource

  respond_to :js

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user_id: current_user.id)))
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def mark_best
    @answer.mark_best if current_user.author?(@answer.question)
    respond_with(@answer)
  end

  def destroy
    @answer.destroy
    respond_with(@answer)
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
      "question_#{@question.id}_answers",
      answer: @answer,
      question_author: @answer.question.user.id,
      attachments: @answer.attachments.map { |a| { id: a.id, file_name: a.file.identifier, file_url: a.file.url } }
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: [:index, :create]
  before_action :set_answer, only: [:show]

  authorize_resource

  def index
    @answers = @question.answers
    respond_with(@answers, each_serializer: AnswersSerializer)
  end

  def show
    respond_with(@answer)
  end

  def create
    @answer = @question.answers.create(answer_params.merge(user_id: current_resource_owner.id))
    respond_with(@answer)
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
    div class=["answer", "answer-#{answer.id}"]
      - cache answer do
        .answer-best
          - if answer.best?
              span.tag.is-warning
                b Answer best
          - elsif can?(:mark_best, answer)
            = link_to 'Mark best', mark_best_answer_path(answer), method: :patch, remote: true, class: 'button is-info is-inverted is-small'
        = answer.body
        = render 'attachments/attachments', entity: answer
        = render 'votes/vote', entity: answer
      - if can?(:update, answer)
          = render 'answers/form_edit', answer: answer
      - if can?(:destroy, answer)
          = link_to 'Delete answer', answer, method: :delete, data: { confirm: 'The answer will be deleted. You are sure?' }, remote: true, class: 'button is-danger is-outlined is-small'
      - cache ['comments', answer] do
        div class=["comments", "comments-answer-#{answer.id}"]
          = render 'comments/show', commentable: answer
      hr

app/views/answers/_form.html.slim
= form_for [question, @answer], remote: true do |f|
  = f.label :body, class: 'label'
  .answer-errors
  p.control
    = f.text_area :body, class: 'textarea'
  = render 'attachments/form', f: f, attach: @answer.attachments.build
  = f.submit 'Add new answer', class: 'button is-info'

app/views/answers/_form_edit.html.slim
div
  = link_to 'Edit', '', class: 'edit-answer-link button is-success is-outlined is-small', data: { answer_id: answer.id }
div.answer-edit
  = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
    = f.label :body, 'Answer', class: 'label'
    p.control
      = f.text_area :body, id: "body-answer-#{answer.id}", class: 'textarea'
    = f.submit 'Save', class: 'button is-success is-outlined'

app/views/answers/create.js.erb
$('.answer-errors').html('');
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').append('<span><%= j message %></span>');
    <% end %>
<% else %>
    $('.answers').append('<%= j render @answer %>');
    $('#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $('.answer-<%= @answer.id %>').remove();
  $('.notice').html('Answer was successfully destroyed.');
<% else %>
  $('.alert').html('You can not remove an answer!');
<% end %>

app/views/answers/mark_best.js.erb
$('.answers').html('<%= j render @answer.question.answers.first_best %>');

app/views/answers/update.js.erb
$('.answer-errors').html('');
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').append('<span><%= j message %></span>');
    <% end %>
<% else %>
    $('.answer-<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>